-- Project Management Program: initial schema (CLAUDE.md §5).
-- Portable between H2 (MODE=PostgreSQL) and PostgreSQL: VARCHAR + CHECK instead of enums.

CREATE TABLE employee (
    employee_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(100)  NOT NULL,
    email                VARCHAR(255)  NOT NULL,
    password_hash        VARCHAR(100)  NOT NULL,
    role                 VARCHAR(20)   NOT NULL CHECK (role IN ('SALE', 'PRESALE', 'PM', 'TECH')),
    profile_picture_path VARCHAR(500),
    created_at           TIMESTAMP     NOT NULL,
    CONSTRAINT uq_employee_email UNIQUE (email)
);

CREATE TABLE engineer_skill (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT       NOT NULL REFERENCES employee (employee_id),
    skill       VARCHAR(100) NOT NULL,
    CONSTRAINT uq_engineer_skill UNIQUE (employee_id, skill)
);

CREATE TABLE project (
    project_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name   VARCHAR(200)  NOT NULL,
    customer_name  VARCHAR(200)  NOT NULL,
    customer_email VARCHAR(255)  NOT NULL,
    sale_id        BIGINT        NOT NULL REFERENCES employee (employee_id),
    presale_id     BIGINT        NOT NULL REFERENCES employee (employee_id),
    pm_id          BIGINT        REFERENCES employee (employee_id),
    objective      VARCHAR(4000),
    est_budget     NUMERIC(15, 2),
    start_date     DATE,
    end_date       DATE,
    status         VARCHAR(40)   NOT NULL CHECK (status IN ('NEW_PROJECT', 'WAITING_FOR_ASSIGN_ENGINEER',
                                   'WORKING', 'TESTING', 'WAITING_FOR_APPROVE', 'FINISH')),
    created_by     BIGINT        NOT NULL REFERENCES employee (employee_id),
    created_at     TIMESTAMP     NOT NULL,
    updated_at     TIMESTAMP     NOT NULL,
    version        BIGINT        NOT NULL DEFAULT 0,
    -- Project Site address
    building_no    VARCHAR(50)   NOT NULL,
    village_no     VARCHAR(50),
    alley          VARCHAR(100),
    soi            VARCHAR(100),
    street         VARCHAR(100),
    subdistrict    VARCHAR(100)  NOT NULL,
    district       VARCHAR(100)  NOT NULL,
    province       VARCHAR(100)  NOT NULL,
    zipcode        VARCHAR(10)   NOT NULL
);

CREATE TABLE project_engineer (
    project_id  BIGINT    NOT NULL REFERENCES project (project_id),
    employee_id BIGINT    NOT NULL REFERENCES employee (employee_id),
    assigned_by BIGINT    NOT NULL REFERENCES employee (employee_id),
    assigned_at TIMESTAMP NOT NULL,
    PRIMARY KEY (project_id, employee_id)
);

CREATE TABLE requirement (
    requirement_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id      BIGINT        NOT NULL REFERENCES project (project_id),
    title           VARCHAR(200)  NOT NULL,
    detail          VARCHAR(4000) NOT NULL,
    priority        VARCHAR(10)   NOT NULL CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    due_date        DATE          NOT NULL,
    related_feature VARCHAR(200),
    status          VARCHAR(20)   NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    reject_reason   VARCHAR(1000),
    created_by      BIGINT        NOT NULL REFERENCES employee (employee_id),
    created_at      TIMESTAMP     NOT NULL,
    decided_by      BIGINT        REFERENCES employee (employee_id),
    decided_at      TIMESTAMP,
    version         BIGINT        NOT NULL DEFAULT 0
);

CREATE TABLE project_document (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id     BIGINT       NOT NULL REFERENCES project (project_id),
    requirement_id BIGINT       REFERENCES requirement (requirement_id),
    type           VARCHAR(30)  NOT NULL CHECK (type IN ('SOLUTION', 'PRODUCT_REQUIREMENT', 'REQUIREMENT_ATTACHMENT')),
    original_name  VARCHAR(255) NOT NULL,
    file_path      VARCHAR(500) NOT NULL,
    mime           VARCHAR(100) NOT NULL,
    size_bytes     BIGINT       NOT NULL,
    uploaded_by    BIGINT       NOT NULL REFERENCES employee (employee_id),
    uploaded_at    TIMESTAMP    NOT NULL
);

CREATE TABLE project_test_schedule (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT        NOT NULL REFERENCES project (project_id),
    test_at    TIMESTAMP     NOT NULL,
    detail     VARCHAR(2000) NOT NULL,
    created_by BIGINT        NOT NULL REFERENCES employee (employee_id),
    created_at TIMESTAMP     NOT NULL
);

CREATE TABLE notification (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT        NOT NULL REFERENCES employee (employee_id),
    project_id   BIGINT        REFERENCES project (project_id),
    type         VARCHAR(50)   NOT NULL,
    message      VARCHAR(1000) NOT NULL,
    send_at      TIMESTAMP     NOT NULL,
    read_at      TIMESTAMP,
    created_at   TIMESTAMP     NOT NULL
);

CREATE INDEX ix_project_status       ON project (status);
CREATE INDEX ix_project_sale         ON project (sale_id);
CREATE INDEX ix_requirement_project  ON requirement (project_id, status);
CREATE INDEX ix_notification_inbox   ON notification (recipient_id, read_at, send_at);
